CREATE TABLE `sensitive_words` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `uniq_id` varchar(200) DEFAULT NULL COMMENT 'word唯一标识，md5值',
  `business_scene` varchar(200) DEFAULT NULL COMMENT '业务场景',
  `word` varchar(1000) DEFAULT NULL COMMENT '敏感词',
  `class_name` varchar(500) DEFAULT NULL COMMENT '分类，多级分类使用`/`分隔',
  `class_no` varchar(500) DEFAULT NULL COMMENT '分类编码',
  `tags` varchar(200) DEFAULT NULL COMMENT '敏感词标签，用于指定场景用途细分',
  `match_type` varchar(20) DEFAULT NULL COMMENT '匹配query的策略，contain(包含)，equal(相等), regex(正则), compound(组合), ... ...',
  `handle_strategy` varchar(20) DEFAULT NULL COMMENT '处置策略，black(黑名单)、white(白名单)、gray(灰名单)、... ...',
  `source` varchar(100) DEFAULT NULL COMMENT '数据来源',
  `desc` text COMMENT '备注',
  `version` int(11) NOT NULL DEFAULT '-1' COMMENT '版本',
  `status` varchar(20) NOT NULL COMMENT '状态，offline(已下线)、online(已上线)、... ...',
  `editor_erp` varchar(50) DEFAULT NULL COMMENT '编辑者用户标识',
  `editor_name` varchar(50) DEFAULT NULL COMMENT '编辑者姓名',
  `auditor_erp` varchar(50) DEFAULT NULL COMMENT '审核者用户标识',
  `auditor_name` varchar(50) DEFAULT NULL COMMENT '审核者姓名',
  `release_erp` varchar(50) DEFAULT NULL COMMENT '发布者用户标识',
  `release_name` varchar(50) DEFAULT NULL COMMENT '发布者姓名',
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  `update_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间戳',
  `first_class_name` varchar(255) DEFAULT NULL COMMENT '一级分类名称',
  `first_class_no` int(11) DEFAULT NULL COMMENT '一级分类编号',
  `second_class_name` varchar(255) DEFAULT NULL COMMENT '二级分类名称',
  `second_class_no` int(11) DEFAULT NULL COMMENT '二级分类编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_word` (`uniq_id`,`business_scene`,`version`),
  KEY `word` (`word`(50))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='敏感词表';


CREATE TABLE `business_info` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `name` varchar(255) NOT NULL COMMENT '业务名',
  `group` varchar(50) DEFAULT 'default' COMMENT '分组部署时对应分组名',
  `desc` varchar(255) DEFAULT NULL COMMENT '业务描述',
  `type` varchar(50) DEFAULT NULL COMMENT '类型',
  `secret_key` varchar(255) NOT NULL COMMENT '密钥',
  `access_targets` text COMMENT '授权对象，例子：["defenseV2","defenseResultV2"]',
  `qps_limit` int(11) DEFAULT NULL COMMENT '总QPS限制',
  `robot_check_conf` text COMMENT '生成内容检测相关配置，json格式，例子：{"checkNum": 1,"unit": "message_single","timeoutMilliseconds": 200}',
  `user_check_conf` text COMMENT '用户检测相关配置，json格式，例子：{"checkNum": 1,"unit": "message_single","timeoutMilliseconds": 200}',
  `version` int(11) NOT NULL DEFAULT '-1' COMMENT '版本',
  `status` varchar(20) NOT NULL COMMENT '状态，offline(已下线)、online(已上线)、... ...',
  `editor_erp` varchar(50) DEFAULT NULL COMMENT '编辑者用户标识',
  `editor_name` varchar(50) DEFAULT NULL COMMENT '编辑者姓名',
  `auditor_erp` varchar(50) DEFAULT NULL COMMENT '审核者用户标识',
  `auditor_name` varchar(50) DEFAULT NULL COMMENT '审核者姓名',
  `release_erp` varchar(50) DEFAULT NULL COMMENT '发布者用户标识',
  `release_name` varchar(50) DEFAULT NULL COMMENT '发布者姓名',
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  `update_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_name` (`name`,`group`,`version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='业务信息表';

CREATE TABLE `execute_dag_conf` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `business_name` varchar(50) NOT NULL COMMENT '业务名称',
  `group` varchar(50) DEFAULT NULL COMMENT '分组部署时对应分组名',
  `desc` varchar(255) DEFAULT NULL COMMENT '描述',
  `root_id` varchar(255) DEFAULT NULL COMMENT '链根ID',
  `conf` text COMMENT 'dag配置，json数组',
  `version` int(11) NOT NULL DEFAULT '-1' COMMENT '版本',
  `status` varchar(20) NOT NULL COMMENT '状态，offline(已下线)、online(已上线)、... ...',
  `editor_erp` varchar(50) DEFAULT NULL COMMENT '编辑者用户标识',
  `editor_name` varchar(50) DEFAULT NULL COMMENT '编辑者姓名',
  `auditor_erp` varchar(50) DEFAULT NULL COMMENT '审核者用户标识',
  `auditor_name` varchar(50) DEFAULT NULL COMMENT '审核者姓名',
  `release_erp` varchar(50) DEFAULT NULL COMMENT '发布者用户标识',
  `release_name` varchar(50) DEFAULT NULL COMMENT '发布者姓名',
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  `update_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_name` (`business_name`,`group`,`version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='执行dag配置表';


CREATE TABLE `function_conf` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `name` varchar(50) NOT NULL COMMENT '原子能力名称',
  `group` varchar(50) DEFAULT NULL COMMENT '分组部署时对应分组名',
  `desc` varchar(255) DEFAULT NULL COMMENT '描述',
  `type` varchar(50) NOT NULL COMMENT '原子能力类型',
  `timeout_milliseconds` bigint(11) DEFAULT NULL COMMENT '超时时间',
  `conf` text COMMENT '原子能力配置项,JSON格式',
  `version` int(11) NOT NULL DEFAULT '-1' COMMENT '版本',
  `status` varchar(20) NOT NULL COMMENT '状态，offline(已下线)、online(已上线)、... ...',
  `editor_erp` varchar(50) DEFAULT NULL COMMENT '编辑者用户标识',
  `editor_name` varchar(50) DEFAULT NULL COMMENT '编辑者姓名',
  `auditor_erp` varchar(50) DEFAULT NULL COMMENT '审核者用户标识',
  `auditor_name` varchar(50) DEFAULT NULL COMMENT '审核者姓名',
  `release_erp` varchar(50) DEFAULT NULL COMMENT '发布者用户标识',
  `release_name` varchar(50) DEFAULT NULL COMMENT '发布者姓名',
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  `update_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_name` (`name`,`group`,`version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='原子能力配置表';


CREATE TABLE `red_line_knowledge` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `uniq_id` varchar(200) DEFAULT NULL COMMENT '唯一标识，md5值',
  `business_scene` varchar(200) DEFAULT NULL COMMENT '业务场景',
  `question` text COMMENT '问题',
  `answer` text COMMENT '答案',
  `metadata` text COMMENT '额外信息',
  `class_name` varchar(500) DEFAULT NULL COMMENT '分类，多级分类使用`/`分隔',
  `class_no` bigint(20) DEFAULT NULL COMMENT '分类编码',
  `source` varchar(100) DEFAULT NULL COMMENT '数据来源',
  `type` varchar(100) DEFAULT NULL COMMENT '类别，如时事、观点、其它',
  `desc` text COMMENT '备注',
  `version` int(11) NOT NULL DEFAULT '-1' COMMENT '版本',
  `status` varchar(20) NOT NULL COMMENT '状态，offline(已下线)、online(已上线)、... ...',
  `editor_erp` varchar(50) DEFAULT NULL COMMENT '编辑者用户标识',
  `editor_name` varchar(50) DEFAULT NULL COMMENT '编辑者姓名',
  `auditor_erp` varchar(50) DEFAULT NULL COMMENT '审核者用户标识',
  `auditor_name` varchar(50) DEFAULT NULL COMMENT '审核者姓名',
  `release_erp` varchar(50) DEFAULT NULL COMMENT '发布者用户标识',
  `release_name` varchar(50) DEFAULT NULL COMMENT '发布者姓名',
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  `update_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_knowledge` (`uniq_id`,`business_scene`,`version`),
  KEY `question` (`question`(50)),
  KEY `idx_type` (`type`(50)),
  KEY `idx_source` (`source`(50)),
  KEY `idx_question` (`question`(50))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='红线知识表';


CREATE TABLE `platform_dict` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `key` varchar(255) NOT NULL COMMENT '用户名',
  `value` text COMMENT '配置详情，json格式',
  `version` int(11) NOT NULL COMMENT '版本',
  `desc` varchar(500) DEFAULT NULL COMMENT '描述',
  `status` varchar(20) NOT NULL COMMENT '状态，offline(已下线)、online(已上线)、... ...',
  `release_erp` varchar(50) DEFAULT NULL COMMENT '发布者用户标识',
  `release_name` varchar(50) DEFAULT NULL COMMENT '发布者姓名',
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  `update_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间戳',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_key_version` (`key`,`version`),
  KEY `idx_update_time` (`update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='字典表';