name: Test
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
      
      - name: Set up environment variables
        run: |
          echo "SAFETY_ROOT_PATH=$PWD" >> $GITHUB_ENV
          echo "SAFETY_MODEL_DIR=$PWD/data/models" >> $GITHUB_ENV

      - name: prepare the models
        run: |
          git lfs install
          git clone https://huggingface.co/jdopensource/JoySafety ${SAFETY_ROOT_PATH}/data/models
          cd $SAFETY_ROOT_PATH        

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yaml"
        env:
          SAFETY_ROOT_PATH:  ${{ env.SAFETY_ROOT_PATH }}
          SAFETY_MODEL_DIR:  ${{ env.SAFETY_MODEL_DIR }}
          REDIS_PASSWORD: 123456
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_PASSWORD: 123456

      - name: Execute tests in the running services
        run: |
          sleep 100s
          docker cp quickstart/api_test.py safety-knowledge:/work/api_test.py
          docker exec -it safety-knowledge python /work/api_test.py '你好'
