name: Test
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SAFETY_ROOT_PATH: "$pwd"
      SAFETY_MODEL_DIR: ${SAFETY_ROOT_PATH}/data/models
      REDIS_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_PASSWORD: 123456

    steps:
      - uses: actions/checkout@v4.2.2

      - name: prepare the models
        env:
          SAFETY_ROOT_PATH: "$pwd"
        run: |
          git lfs install
          git clone https://huggingface.co/jdopensource/JoySafety ${SAFETY_ROOT_PATH}/data/models
          cd $SAFETY_ROOT_PATH        

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yaml"
        env:
          SAFETY_ROOT_PATH: "$pwd"
          SAFETY_MODEL_DIR: ${SAFETY_ROOT_PATH}/data/models
          REDIS_PASSWORD: 123456
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_PASSWORD: 123456

      - name: Execute tests in the running services
        run: |
          docker cp quickstart/api_test.py safety-knowledge:/work/api_test.py
          docker exec -it safety-knowledge python /work/api_test.py '你好'
